// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUylXSkbriiDpzEedUWsnc3qgtJ-7uj6k',
    appId: '1:23157116164:web:f17eea7315a2a46066d451',
    messagingSenderId: '23157116164',
    projectId: 'crud-app-e3f9f',
    authDomain: 'crud-app-e3f9f.firebaseapp.com',
    databaseURL: 'https://crud-app-e3f9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-e3f9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJDWZpL6JRPRovjY7-JB14TaX14qAcN0',
    appId: '1:23157116164:android:cf951fea00081e8466d451',
    messagingSenderId: '23157116164',
    projectId: 'crud-app-e3f9f',
    databaseURL: 'https://crud-app-e3f9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-e3f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtVGfKLImUrIt7batCZlnTBwfeha7Emsg',
    appId: '1:23157116164:ios:ab70348c82202d2d66d451',
    messagingSenderId: '23157116164',
    projectId: 'crud-app-e3f9f',
    databaseURL: 'https://crud-app-e3f9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-e3f9f.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtVGfKLImUrIt7batCZlnTBwfeha7Emsg',
    appId: '1:23157116164:ios:af76f8f1c043a15b66d451',
    messagingSenderId: '23157116164',
    projectId: 'crud-app-e3f9f',
    databaseURL: 'https://crud-app-e3f9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-e3f9f.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
